name: Run tests and deploy image

on:
  push:
  pull_request:
    branches: [trufi]

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        run: npm test

  docker:
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/trufi' }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::313329311652:role/PushContainerImagesGithubActions
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Publish to Amazon ECR
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hbt/photon-pelias-adapter
          username: ${{ steps.login-ecr.outputs.username }}
          password: ${{ steps.login-ecr.outputs.password }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          tags: "latest,${{ github.sha }}"
